GET http://localhost:3000/cafehermanos
###
GET http://localhost:3000/cafehermanos/60dd58bb36584b1a288d15d3
###

POST http://localhost:3000/cafehermanos
Content-Type: application/json
{
    "name": "ahmet",
    "surname": "kırmızı"
}

###
DELETE http://localhost:3000/cafehermanos/60dc827be0d61c17446d7608
###
PATCH http://localhost:3000/cafehermanos/60dc83634ccf912918f41428
Content-Type: application/json
{
    "name" : "new name" 
}